### ISSUE TITLE
STD/Variance don't work with 1 minute setting

### ISSUE THREAD

**Issue by ilcartographer** [ilcartographer/embrace-visualization#51]
Previously, we had disabled the 1-minute setting for this reason, but I've re-enabled it to meet our initial requirements.  The other metrics seem to work fine.
This is noted in the readme as a defect, but it would be good to figure out why std and variance don't work with 1 minute sampling.

**Comment by Jonathan-Dickinson** [comment]
I have been looking into this and I think I found something. I think what is happening is that with variance and standard deviation, it is taking into account the mean for 1 minute intervals. The data provided to us has a data point generated every 1 minute, so when it is taking the variance or deviation with itself, it is always 0, which is why a flat line appears when the 1 minute option is used with these metric settings. I'm not sure if this is right, but please let me know what you think. If this is what is happening, we could put the 1 minute option back, since it works with the other settings and would fulfill our original requirements.

**Comment by ilcartographer** [comment]
That actually makes perfect sense to me! You have to have at least two values, so that would explain it. I went ahead and re-enabled it, and left the 2 minute interval. I'll add a note on the readme to clarify this. Thanks for looking into it!!
